[functions]
  external_node_modules = ["express", "@libsql/client", "cors", "dotenv"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/:splat"