[functions]
  external_node_modules = ["@nestjs/core", "@nestjs/common", "@nestjs/platform-express", "@libsql/client", "cors", "dotenv"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.src/:splat"

[build]
  command = "npm run build"
  publish = "dist"
