[functions]
  external_node_modules = ["@nestjs/core", "@nestjs/common", "@nestjs/platform-express", "@libsql/client", "cors", "dotenv", "class-transformer", "reflect-metadata"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  command = "npm run build"
  publish = "dist/src"
  functions = "dist/netlify/functions/"
